### ISSUE TITLE
Neveikia projektas

### ISSUE THREAD

**Issue by driuba** [andrikonis/Asteroids#11]
Nepasileidžia projektas, žaidimas visiškai neveikia.

**Comment by driuba** [comment]
Tiriama klaida, pavyksta atkartoti

**Comment by GedAus** [comment]
Ta pati problema, pavyksta atkartoti

**Comment by Donce530** [comment]
Man irgi neveikia ¯\\_(ツ)_/¯

**Comment by driuba** [comment]
Trūksta SFML bibliotekų. Naudojami Assembly failai blogai pavadinti.

**Comment by andrikonis** [comment]
Suinstaliuotas NuGet SFML plėtitnys, pervadinti _Assembly_ failai

**Comment by driuba** [comment]
Suinstaliuotas NuGet SFML plėtitnys, pervadinti Assembly failai
